// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdMWe6p2uAGvKcrE7Ve2-2-kXiBosOog',
    appId: '1:628471721601:web:c2ce9caca97d9759182780',
    messagingSenderId: '628471721601',
    projectId: 'loja-virtual-470d0',
    authDomain: 'loja-virtual-470d0.firebaseapp.com',
    storageBucket: 'loja-virtual-470d0.appspot.com',
    measurementId: 'G-C5MLVHBH40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_XKhilZxamQXv5vL9b4Ew-x6R6sDG1A',
    appId: '1:628471721601:android:4b7b9ad5d3c25008182780',
    messagingSenderId: '628471721601',
    projectId: 'loja-virtual-470d0',
    storageBucket: 'loja-virtual-470d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFunNU5FHNH4UxT2rWJiFe90y8h4xkwI',
    appId: '1:628471721601:ios:17b85209719cd720182780',
    messagingSenderId: '628471721601',
    projectId: 'loja-virtual-470d0',
    storageBucket: 'loja-virtual-470d0.appspot.com',
    iosClientId: '628471721601-q3d2gfpqcr53mh3fcovmv05im618d5a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFunNU5FHNH4UxT2rWJiFe90y8h4xkwI',
    appId: '1:628471721601:ios:17b85209719cd720182780',
    messagingSenderId: '628471721601',
    projectId: 'loja-virtual-470d0',
    storageBucket: 'loja-virtual-470d0.appspot.com',
    iosClientId: '628471721601-q3d2gfpqcr53mh3fcovmv05im618d5a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.green',
  );
}
